version: "3.8" # 🧾 Compose file format version

services: # 🧱 Services to run — each is like a mini computer
  postgres: # 👨‍🔧 Name of the service (you can call it anything)
    image: postgres:15 # 📦 Download the official PostgreSQL version 15
    container_name: bookstore-postgres # 🏷️ Name the container (for reference)
    restart: always # 🔄 Restart if it crashes
    environment: # 🌍 Set up environment variables for the DB
      POSTGRES_USER: postgres # Username = postgres
      POSTGRES_PASSWORD: secret # Password = secret
      POSTGRES_DB: bookstore # Database = bookstore
    ports: # 🌐 Expose the container's port to your machine
      - "5432:5432" # containerPort:hostPort
    volumes: # 💾 Persist data so DB isn't lost when restarting
      - pg_data:/var/lib/postgresql/data

volumes: # 🔒 Declare volume to persist database storage
  pg_data:
