// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/bookStore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookIdRequest) Reset() {
	*x = BookIdRequest{}
	mi := &file_proto_bookStore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookIdRequest) ProtoMessage() {}

func (x *BookIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookStore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookIdRequest.ProtoReflect.Descriptor instead.
func (*BookIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookStore_proto_rawDescGZIP(), []int{0}
}

func (x *BookIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BookDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookDetailResponse) Reset() {
	*x = BookDetailResponse{}
	mi := &file_proto_bookStore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDetailResponse) ProtoMessage() {}

func (x *BookDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookStore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDetailResponse.ProtoReflect.Descriptor instead.
func (*BookDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_bookStore_proto_rawDescGZIP(), []int{1}
}

func (x *BookDetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookDetailResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookDetailResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookDetailResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BooksDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*BookDetailResponse  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksDetailResponse) Reset() {
	*x = BooksDetailResponse{}
	mi := &file_proto_bookStore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksDetailResponse) ProtoMessage() {}

func (x *BooksDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookStore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksDetailResponse.ProtoReflect.Descriptor instead.
func (*BooksDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_bookStore_proto_rawDescGZIP(), []int{2}
}

func (x *BooksDetailResponse) GetBooks() []*BookDetailResponse {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_proto_bookStore_proto protoreflect.FileDescriptor

const file_proto_bookStore_proto_rawDesc = "" +
	"\n" +
	"\x15proto/bookStore.proto\x12\tbookStore\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n" +
	"\rBookIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\x12BookDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\"J\n" +
	"\x13BooksDetailResponse\x123\n" +
	"\x05books\x18\x01 \x03(\v2\x1d.bookStore.BookDetailResponseR\x05books2\x97\x01\n" +
	"\tBookStore\x12D\n" +
	"\aGetById\x12\x18.bookStore.BookIdRequest\x1a\x1d.bookStore.BookDetailResponse\"\x00\x12D\n" +
	"\bGetBooks\x12\x16.google.protobuf.Empty\x1a\x1e.bookStore.BooksDetailResponse\"\x00B\x16Z\x14grpc-bookStore/protob\x06proto3"

var (
	file_proto_bookStore_proto_rawDescOnce sync.Once
	file_proto_bookStore_proto_rawDescData []byte
)

func file_proto_bookStore_proto_rawDescGZIP() []byte {
	file_proto_bookStore_proto_rawDescOnce.Do(func() {
		file_proto_bookStore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bookStore_proto_rawDesc), len(file_proto_bookStore_proto_rawDesc)))
	})
	return file_proto_bookStore_proto_rawDescData
}

var file_proto_bookStore_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_bookStore_proto_goTypes = []any{
	(*BookIdRequest)(nil),       // 0: bookStore.BookIdRequest
	(*BookDetailResponse)(nil),  // 1: bookStore.BookDetailResponse
	(*BooksDetailResponse)(nil), // 2: bookStore.BooksDetailResponse
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_proto_bookStore_proto_depIdxs = []int32{
	1, // 0: bookStore.BooksDetailResponse.books:type_name -> bookStore.BookDetailResponse
	0, // 1: bookStore.BookStore.GetById:input_type -> bookStore.BookIdRequest
	3, // 2: bookStore.BookStore.GetBooks:input_type -> google.protobuf.Empty
	1, // 3: bookStore.BookStore.GetById:output_type -> bookStore.BookDetailResponse
	2, // 4: bookStore.BookStore.GetBooks:output_type -> bookStore.BooksDetailResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bookStore_proto_init() }
func file_proto_bookStore_proto_init() {
	if File_proto_bookStore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bookStore_proto_rawDesc), len(file_proto_bookStore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bookStore_proto_goTypes,
		DependencyIndexes: file_proto_bookStore_proto_depIdxs,
		MessageInfos:      file_proto_bookStore_proto_msgTypes,
	}.Build()
	File_proto_bookStore_proto = out.File
	file_proto_bookStore_proto_goTypes = nil
	file_proto_bookStore_proto_depIdxs = nil
}
